# - name: Load NodeJS
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: nodejs

# - name: App Pre Setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: app-setup.yaml

# - name: Install node dependencies
#   ansible.builtin.shell: npm install
#   args:
#       chdir: /app

# - name: SystemD Setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: systemd-setup.yaml

- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.joindevops.online < /app/schema/catalogue.js